### ISSUE TITLE
Split Bam Error 2

### ISSUE THREAD

**Issue by sph17** [cortes-ciriano-lab/SComatic#35]
Hi, I am trying to run a sample through SComatic. When I run splitbam 

I am getting this error: 

```
SCOMATIC=/restricted/projectnb/findthecause/scRNAseq_mutdec/SComatic
output_dir=/restricted/projectnb/findthecause/scRNAseq_mutdec/results/pt13
sample=BUMC_LR_013_T

(SComatic)[sphao@scc4 data]$ python $SCOMATIC/scripts/SplitBam/SplitBamCellTypes.py --bam BUMC_LR_013_T_possorted_genome_bam.bam \
>         --meta pt13_annotations.tsv \
>         --id ${sample} \
>         --outdir $output_dir
[E::hts_open_format] Failed to open file "/restricted/projectnb/findthecause/scRNAseq_mutdec/results/pt13/BUMC_LR_013_T.Monocyte/Macrophage.bam" : No such file or directory
Traceback (most recent call last):
  File "/restricted/projectnb/findthecause/scRNAseq_mutdec/SComatic/scripts/SplitBam/SplitBamCellTypes.py", line 221, in <module>
    main()
  File "/restricted/projectnb/findthecause/scRNAseq_mutdec/SComatic/scripts/SplitBam/SplitBamCellTypes.py", line 213, in main
    split_bam(bam, txt, outdir,donor,tissue,max_NM,max_NH,min_MAPQ,n_trim)
  File "/restricted/projectnb/findthecause/scRNAseq_mutdec/SComatic/scripts/SplitBam/SplitBamCellTypes.py", line 49, in split_bam
    outfile_wb = pysam.AlignmentFile(outfile, "wb",template=infile)
  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 915, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] could not open alignment file `/restricted/projectnb/findthecause/scRNAseq_mutdec/results/pt13/BUMC_LR_013_T.Monocyte/Macrophage.bam`: No such file or directory

```

The annotation file looks like this: 
<img width="465" alt="image" src="https://github.com/cortes-ciriano-lab/SComatic/assets/64153168/4a36601f-918f-4715-9259-a022ef7fbde9">

**Comment by Francesc-Muyas** [comment]
Dear user, 
Does the folder ${output_dir} exist?

Thanks, 
Frn

**Comment by sph17** [comment]
Hi Fran, 

Thanks for getting back to me.
I checked `cut -f2 pt13_annotations.tsv | sort | uniq -c` and was able to locate the problem as an annotation formatted as `Monocyte/Macrophage`. Once I removed the `/`, it fixed the error. Thanks so much for your help!
