### ISSUE TITLE
start > stop

### ISSUE THREAD

**Issue by xuxif** [cortes-ciriano-lab/SComatic#60]
Traceback (most recent call last):
  File "/home/xuxf/bin/SComatic-main//scripts/SitesPerCell/SitesPerCell.py", line 369, in <module>
    main()
  File "/home/xuxf/bin/SComatic-main//scripts/SitesPerCell/SitesPerCell.py", line 358, in main
    collect_result(run_interval(row, DICT_sites[row], BAM, FASTA, MIN_COV, MIN_CC, tmp_dir, MIN_BQ, MIN_MQ))
  File "/home/xuxf/bin/SComatic-main//scripts/SitesPerCell/SitesPerCell.py", line 131, in run_interval
    i = bam.pileup(CHROM, START, END, min_base_quality = BQ, min_mapping_quality = MQ, ignore_overlaps = False)
  File "pysam/libcalignmentfile.pyx", line 1326, in pysam.libcalignmentfile.AlignmentFile.pileup
  File "pysam/libchtslib.pyx", line 688, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid coordinates: start (248838337) > stop (140010)

**Comment by Francesc-Muyas** [comment]
Dear user, 
Thanks for bringing this up. I think I fixed the problem and edited the script accordingly. 
Could you pull the repo and check the script again?

Thanks, 
Fran
